### ISSUE TITLE
Doesn't build with base-4.12.0.0

### ISSUE THREAD

**Issue by k0001** [nikita-volkov/rebase#12]
```
[317 of 358] Compiling Rebase.GHC.PArr  ( library/Rebase/GHC/PArr.hs, dist/build/Rebase/GHC/PArr.o )

library/Rebase/GHC/PArr.hs:7:1: error:                                                                   
    Could not find module ‘GHC.PArr’                                                                     
    Perhaps you meant
      GHC.Arr (from base-4.12.0.0)
      GHC.Err (from base-4.12.0.0)
      GHC.Ptr (from base-4.12.0.0)
    Use -v to see a list of the files searched for.
  |
7 | import GHC.PArr
  | ^^^^^^^^^^^^^^^
```

**Comment by nikita-volkov** [comment]
Fixed
