### ISSUE TITLE
Doesn't build with GHC 8.2.1

### ISSUE THREAD

**Issue by nh2** [nikita-volkov/rebase#9]
Build error:

```
library/Rebase/Prelude.hs:9:3: error:
    Conflicting exports for ‘fromLeft’:
       ‘module Exports’ exports ‘Exports.fromLeft’
         imported from ‘BasePrelude’ at library/Rebase/Prelude.hs:16:1-63
         (and originally defined in ‘Data.Either’)
       ‘module Exports’ exports ‘Exports.fromLeft’
         imported from ‘Rebase.Data.Either.Combinators’ at library/Rebase/Prelude.hs:83:1-92
         (and originally defined in ‘Data.Either.Combinators’)
  |
9 |   module Exports,
  |   ^^^^^^^^^^^^^^

library/Rebase/Prelude.hs:9:3: error:
    Conflicting exports for ‘fromRight’:
       ‘module Exports’ exports ‘Exports.fromRight’
         imported from ‘BasePrelude’ at library/Rebase/Prelude.hs:16:1-63
         (and originally defined in ‘Data.Either’)
       ‘module Exports’ exports ‘Exports.fromRight’
         imported from ‘Rebase.Data.Either.Combinators’ at library/Rebase/Prelude.hs:83:1-92
         (and originally defined in ‘Data.Either.Combinators’)
  |
9 |   module Exports,
  |   ^^^^^^^^^^^^^^
```

Probably due to the now `fromLeft`/`fromRight` functions: https://downloads.haskell.org/%7Eghc/8.2.1/docs/html/users_guide/8.2.1-notes.html#base

> Data.Either now provides fromLeft and fromRight

**Comment by nikita-volkov** [comment]
Fixed
