### ISSUE TITLE
Doesn't build with semigroupoids 5.2.2

### ISSUE THREAD

**Issue by felixonmars** [nikita-volkov/rebase#10]
```
[336 of 358] Compiling Rebase.Prelude   ( library/Rebase/Prelude.hs, dist/build/Rebase/Prelude.dyn_o )

library/Rebase/Prelude.hs:9:3: error:
    Conflicting exports for ‘optional’:
       ‘module Exports’ exports ‘Exports.optional’
         imported from ‘BasePrelude’ at library/Rebase/Prelude.hs:16:1-63
         (and originally defined in ‘Control.Applicative’)
       ‘module Exports’ exports ‘Exports.optional’
         imported from ‘Rebase.Data.Functor.Plus’ at library/Rebase/Prelude.hs:53:1-68
         (and originally defined in ‘Data.Functor.Alt’)
  |
9 |   module Exports,
  |   ^^^^^^^^^^^^^^
```

**Comment by felixonmars** [comment]
This has been fixed in 1.2.3. Thanks.
